name = "Lenticulum"
uuid = "80a378fd-9e01-49e8-9939-ada6559002ad"
authors = ["DanielBoigk <71269893+DanielBoigk@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
